### ISSUE TITLE
Зависимости 

### ISSUE THREAD

**Issue by subsender** [Assisted-Mindfulness/naive-bayes#4]
Отличная реализация!

Но, есть огромный минус - это зависимости. Для проекта который выполнен на другом фреймворке надо тащить за собой зависимости ларавел.

Было бы очень хорошо, если ваша реализация была самодостаточная, без зависимостей.

Жаль, что нельзя воспользоваться в реальном проекте.

**Comment by tabuna** [comment]
По поводу зависимостей: здесь есть только один компонент Laravel и библиотека для вычислений. В большинстве проектов уже используются различные библиотеки, и это нормально — они облегчают нам жизнь. Вы можете убедиться проверить это, выполнив команду `composer show` в вашем проекте. Скорее всего, вы увидите, что уже используете множество пакетов от разных поставщиков.

Мы пишем на том, что нам по душе, и **у нас нет планов избавляться от библиотек, которые делают нашу работу удобнее**. Если ваш проект требует минимизации зависимостей, то вы можете реализовать собственный форк. Но в целом, я бы не советовал отказываться от решений, которые экономят время.
